name: Release Go App

on:
  push:
    tags:
      - 'v*' # 当推送以 v 开头的 tag（如 v1.0.0）时触发

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Windows
          - {goos: windows, goarch: amd64, binary_name: bmoji-windows-amd64.exe}
          - {goos: windows, goarch: arm64, binary_name: bmoji-windows-arm64.exe}
          # Linux
          - {goos: linux, goarch: amd64, binary_name: bmoji-linux-amd64}
          - {goos: linux, goarch: arm64, binary_name: bmoji-linux-arm64}
          # macOS
          - {goos: darwin, goarch: amd64, binary_name: bmoji-darwin-amd64}
          - {goos: darwin, goarch: arm64, binary_name: bmoji-darwin-arm64}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0 # 交叉编译建议关闭 CGO 以提高成功率
        run: |
          cd back
          go build -v -o "../dist/${{ matrix.binary_name }}" .

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          generate_release_notes: true # 自动根据 commit 记录生成 Release 说明
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
